set nocompatible

" change the mapleader from / to ,
let mapleader=","

source ~/.vim/config/plugins.vim
source ~/.vim/config/settings.vim
source ~/.vim/config/mappings.vim

" runtime macros/matchit.vim

autocmd Filetype gitcommit setlocal spell textwidth=72
autocmd FileType markdown setlocal spell

autocmd BufNewFile,BufRead *.md set ft=markdown
let g:markdown_fenced_languages = ['css', 'javascript', 'js=javascript', 'json=javascript', 'xml', 'html']


" Local config
if filereadable($HOME . "/.vimrc.local")
  source ~/.vimrc.local
endif
