#!/bin/bash

update_brew() {
  brew update && brew upgrade --all && brew upgrade brew-cask

  # Update neovim
  brew reinstall neovim --HEAD
}

update_npm() {
  npm update -g --silent
}

for opt in $@
do
  case $opt in
    --all) all=true ;;
    --brew) brew=true ;;
    --npm) npm=true ;;
    -*|--*) e_warning "Warning: invalid option $opt" ;;
  esac
done

if [[ $all ]]; then
  echo "Update all packages..."
  update_brew
  update_npm
fi

if [[ $brew ]]; then
  echo "Update Homebrew's packages..."
  update_brew
fi

if [[ $npm ]]; then
  echo "Update NPM's packages..."
  update_npm
fi
