#!/bin/sh

cli=/Applications/Karabiner.app/Contents/Library/bin/karabiner

$cli set repeat.wait 30
/bin/echo -n .
$cli set repeat.initial_wait 300
/bin/echo -n .
$cli set option.vimode_fn_hjkl 1
/bin/echo -n .
/bin/echo
