#!/bin/bash

brew_tap() {
  if ! brew tap | grep "${@}" > /dev/null; then
    brew tap "${@}"
  fi
}

brew_install() {
  if ! $(brew list ${@} >/dev/null); then
    brew install ${@}
  fi
}

# Borrowed from https://github.com/MoOx/dotfiles/blob/master/bin/apps
cask_install() {
  if [ ! -d "$1" ] && [ ! -d "/Applications/$1/" ] && [ ! -d "/Applications/$1.app/" ] && [ ! -d "$HOME/Applications/$1.app/" ] && [ ! -d "$HOME/Applications/$1/" ]
  then
    brew cask install $2
  fi
}

brew_run() {
  brew update
  brew upgrade --all

  echo "Homebrew:"
  echo "Installing packages..."

  local -a PACKAGES_NAME=(
    "git"
    "git-extras"
    "zsh"
    "zsh-completions"
    "nvm"
    "macvim --with-override-system-vim --with-python3 --with-python --HEAD"
    "ack"
    "the_silver_searcher"
    "ctags"
    "tmux"
    "tree"
    "pngquant"
    "trash"
    "fontforge"
    "z"
  )

  for index in ${!PACKAGES_NAME[*]}; do
    brew_install ${PACKAGES_NAME[$index]}
  done

  echo "Installing apps..."

  # brew cask
  brew_tap phinze/cask
  brew_install brew-cask
  brew_tap caskroom/versions

  local -a APPS_NAME=(
    "Atom"
    "Google Chrome"
    "Google Chrome Canary"
    "GoogleAppEngineLauncher"
    "Firefox"
    "Firefoxdeveloperedition"
    "Opera"
    "Caffeine"
    "Cloudup"
    "Discord"
    "Dropbox"
    "AppZapper"
    "Dash"
    "Fluid"
    "Flux"
    "Focus"
    "ImageOptim"
    "LimeChat"
    "Skype"
    "Slack"
    "Slowy"
    "Spectacle"
    "Spotify"
    "TorBrowser"
    "Tower"
    "Transmission"
    "Transmit"
    "Versions"
    "VirtualBox"
    "VLC"
    "Karabiner"

    "qlcolorcode"
    "qlstephen"
    "qlmarkdown"
    "quicklook-json"
    "webp-quicklook"
  )

  for index in ${!APPS_NAME[*]}; do
    app=$(echo ${APPS_NAME[$index]} | tr "A-Z" "a-z" | tr " " "-")
    cask_install "${APPS_NAME[$index]}" "$app"
  done

  # names that does not follow the same pattern
  cask_install "Alfred 2" "alfred"
  cask_install "iTerm 2" "iterm2"
}
