#!/bin/bash

gem_install() {
  if ! type ${@} > /dev/null; then
    sudo gem install -n /usr/local/bin ${@}
  fi
}

gem_run() {
  echo "GEM:"
  echo "Installing packages..."

  sudo gem update --system && sudo gem update

  local -a PACKAGES_NAME=(
    "git-up"
    "jekyll"
  )

  for index in ${!PACKAGES_NAME[*]}; do
    gem_install ${PACKAGES_NAME[$index]}
  done
}
