#!/bin/bash

npm_run() {
  echo "NPM:"
  echo "Installing packages..."

  local packages="\
    esformatter \
    eslint \
    grunt-cli \
    gulp \
    httpster \
    mversion \
    nodemon \
    n \
    npm \
    npm-check-updates \
    npm-module-generator \
    pure-prompt \
    updatehammer \
    yo"

  npm i $packages -g --quiet
}
