#!/bin/bash

npm_run() {
  echo "NPM:"
  echo "Installing packages..."

  local packages="\
    cssfmt \
    esformatter \
    esformatter-braces \
    esformatter-collapse-objects \
    esformatter-dot-notation \
    esformatter-literal-notation \
    esformatter-parseint \
    esformatter-quote-props \
    esformatter-quotes \
    esformatter-remove-trailing-commas \
    esformatter-semicolons \
    esformatter-spaced-lined-comment \
    esformatter-var-each \
    eslint \
    gulp \
    httpster \
    mversion \
    nodemon \
    npm \
    npm-check-updates \
    npm-module-generator \
    pure-prompt \
    updatehammer \
    yo"

  npm i $packages -g --quiet
}
